"""add channel link tokens

Revision ID: 1851ca14b7bd
Revises: 236a406a84ac
Create Date: 2026-09-04 12:22:23.438194

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1851ca14b7bd"
down_revision: Union[str, Sequence[str], None] = "236a406a84ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_link_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_link_tokens_token"),
        "channel_link_tokens",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_channel_link_tokens_user_id"),
        "channel_link_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_channel_link_tokens_user_id"), table_name="channel_link_tokens"
    )
    op.drop_index(
        op.f("ix_channel_link_tokens_token"), table_name="channel_link_tokens"
    )
    op.drop_table("channel_link_tokens")
    # ### end Alembic commands ###
