"""add email and hashed_password

Revision ID: ab2182ed00f4
Revises: af0784214fe4
Create Date: 2026-07-23 18:32:22.936475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2182ed00f4'
down_revision: Union[str, Sequence[str], None] = 'af0784214fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("email", sa.String(length=255), nullable=True),
    )

    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
    )

    op.execute(
        """
        UPDATE users
        SET email = 'legacy_' || id || '@lifeeasy.local'
        WHERE email IS NULL
        """
    )

    op.execute(
        """
        UPDATE users
        SET hashed_password = 'legacy_user_cannot_login'
        WHERE hashed_password IS NULL
        """
    )

    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        nullable=False,
    )

    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=255),
        nullable=False,
    )

    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
